# Generated by Django 3.1.4 on 2020-12-31 10:56

from apps.auth.models import code_generator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20201231_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_profile', serialize=False, to='user.user')),
                ('code', models.CharField(default=code_generator, max_length=5)),
            ],
        ),
    ]
