# https://docs.docker.com/compose/compose-file/

version: '3'

services:
  nginx:
    image: nginx:latest  # Should use a fixed version in prod instead of latest?
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt

  backend:
    image: registry.gitlab.propulsion-home.ch/marco/week-7-docker-and-backend-assignment/day-3-gitlab-and-deployment:latest
    restart: always
    command: 'sh /scripts/prod.sh'
    env_file:
      - ./envs/prod.env
    volumes:
      - static-files:/static-files
      - media-files:/media-files
    depends_on:
      - postgres

  postgres:
    image: postgres:latest  # Should use a fixed version in prod instead of latest?
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  static-files:
  media-files: