# Generated by Django 3.1.4 on 2021-01-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210104_1311'),
        ('post', '0003_auto_20210104_1416'),
        ('post', '0004_auto_20210104_1459'),
    ]

    operations = [
    ]
