# Generated by Django 3.1.4 on 2021-01-04 09:24

import apps.registration_profile.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='code',
            field=models.CharField(default=apps.registration_profile.models.code_generator, max_length=5, validators=[django.core.validators.RegexValidator(message='Code must contain exactly 5 numbers from 0-9.', regex='^[0-9]{5}$')]),
        ),
    ]
