# Generated by Django 3.1.4 on 2021-01-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0002_auto_20210104_1416'),
        ('registration_profile', '0002_auto_20210104_1024'),
    ]

    operations = [
    ]
