//Session
export const USER_SIGNIN = "USER_SIGNIN"
export const RESUME_SESSION = "RESUME_SESSION"

//Sign Up
export const SIGNUP_STEP = "SIGNUP_STEP"
export const USER_REGISTRATION = "USER_REGISTRATION"
export const USER_VALIDATION = "USER_VALIDATION"

//Posts
export const POSTS_FILTER = "POSTS_FILTER"
export const POSTS_FETCH = "POSTS_FETCH"
export const POST_LIKE_TOGGLE = "POST_LIKE_TOGGLE"