# Generated by Django 3.1.4 on 2020-12-28 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=150)),
                ('user', models.ManyToManyField(null=True, related_name='hobby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
