# Generated by Django 3.1.4 on 2021-01-14 18:07

import apps.user.models.user_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210114_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.user_models.user_avatar_directory),
        ),
    ]
